### ISSUE TITLE
Can't start .NET test server via COM

### ISSUE THREAD

**Issue by milosmatovic** [SoftingIndustrial/OPC-Classic-SDK#15]
### Issue Description
When attempting to start C# test server using OPC classic demo client (or any other client), the application starts but fails to connect with error 0x80080005: Failed to create OPC server object. 

Local server listed in OPC client:
(please note that `VersionIndependentProgId` is not listed there for some reason, not sure if this would affect things)
![image](https://user-images.githubusercontent.com/88651825/198693582-316869ef-49d3-42b7-8784-4323a55930b2.png)
Error details:
![image](https://user-images.githubusercontent.com/88651825/198693902-3963fc77-8e2a-42ab-a946-e9445896216c.png)

The application seems to be registered OK in windows registry:
![image](https://user-images.githubusercontent.com/88651825/198694897-44aea06a-d57d-481a-9fc0-8b92f90b39d0.png)
![image](https://user-images.githubusercontent.com/88651825/198695386-ed1731f5-c3d8-438c-8f14-6683b3bfc229.png)
![image](https://user-images.githubusercontent.com/88651825/198695468-7a57455a-3fde-49a1-9270-df42fc06f191.png)

### Environment
Windows 10
opc-core-components-redistributables-3.00.108-20191220
Built TBN dll with .NET framework 4.6.1
![image](https://user-images.githubusercontent.com/88651825/198696067-91827584-3c8f-4481-9586-5b2097c9a524.png)

**DCOMCNFG Settings**
![image](https://user-images.githubusercontent.com/88651825/198698105-fb11035f-1c5a-409a-a7c2-7d31b3656a28.png)
![image](https://user-images.githubusercontent.com/88651825/198698229-4581df92-7b96-472c-9251-1400b4a0fd63.png)
![image](https://user-images.githubusercontent.com/88651825/198698290-c9182468-6401-4806-8fe8-fe3741e5f19a.png)
![image](https://user-images.githubusercontent.com/88651825/198698666-86a9f7d8-d3cc-4754-b265-1274fe01bc4c.png)
![image](https://user-images.githubusercontent.com/88651825/198698733-836ea4b1-467d-4a31-9ba5-7757afd2ee4e.png)
![image](https://user-images.githubusercontent.com/88651825/198698772-f3576f93-baa4-4ce7-a1a5-80ac073c7b0f.png)
![image](https://user-images.githubusercontent.com/88651825/198698826-bad54fd3-443f-4cab-97c2-577ab35b2a83.png)

I haven't changed any of the source code before building, could it be something with the instance setup that requires changing? i.e. user permissions
![image](https://user-images.githubusercontent.com/88651825/198696490-cea6c5d5-3150-4a51-bf27-9cbc963f6227.png)

**Comment by ro0ter** [comment]
Please make sure you are using x86 or x64 architecture.

AGAIN: NEVER USE THE ANYCPU CONFIGURATION FOR AN APPLICATION CONTAINING AN OPC SERVER.

Now, to fix your dev system...

1. Either remember your .NET OPC SERVER
2. Or compile the server as x64, run it with /unregserver, then with /reserver and last with /unregserver, then compile as x86 and run it again with the three parameters

The reason behind this advice is that the .NET AnyCpu-built applications always start as x86 processes, then, if the x64 architecture is available, it just-in-time switches to x64 architecture, spawning itself again.. the DCOM governor however has the handle of the x86 process (that is what it spawned through CoCreateInstance), which is no longer valid, therefore all calls fail. If you pay really good attention, you will notice that the DCOM governor spawns your OPC server every DCOM_TIMEOUT interval, but it won't start since the XML DA Port is taken.

Please read the manual next time, before asking.

Captain.

**Comment by ro0ter** [comment]
Hello @milosmatovic

Please make sure you are using x86 or x64 architecture.

AGAIN: NEVER USE THE ANYCPU CONFIGURATION FOR AN APPLICATION CONTAINING AN OPC SERVER.

Now, to fix your deeds... (your dev system)
1. Either rename your .NET OPC SERVER, however you'll remain with an unusable OPC server in the server list...
2. Or compile the server as (A) x64, then run it with (1) /unregserver, then with (2) /reserver and then again with (3) /unregserver. Afterwards compile as (B) x86 and run it with the three (1,2,3) parameters.

The reason behind this advice is that the .NET AnyCpu-built applications always start as x86 processes, then - if the system architecture is x64 - it just-in-tine switches to x64, spawning itself as x64 and immediately exiting (so the x86 process exits, the x64 remains). This is catastrophic for the DCOM Governor, since it loses its handle to the process it previously spawned with CoCreateInstance.

If you are really paying attention, you'll notice your process starts times and again every DCOM_TIMEOUT interval, yet it stops because the XML DA port is in use by the first server instance.

If your server would not have started at all, the XML-DA port should have been already used by another server. Not the case here, as well all see.

So please, read the manual next time before opening an issue.

Additional note: With the Softing OPC Clasic Demo Client you cannot force the DA version through the browsing mode, you'll have to work with the server properties. And yes, you'll have to select the server nose (left-click it) before right-clicking it... (-: don't ask

Regards,
The Captain.

**Comment by milosmatovic** [comment]
Hi @ro0ter , thank you very much for the quick and detailed response. 
Building as x64 has indeed worked! Closing the ticket now.
